name: he_brew_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^4.0.4
  provider: ^6.1.2
  font_awesome_flutter: '>= 9.2.0'
  http: ^0.13.6
  shared_preferences: ^2.0.13
  paymongo_sdk: ^1.7.0
  webview_flutter: ^4.8.0
  webview_flutter_wkwebview: ^3.14.0
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/login/
    - images/iced_drinks/
    - images/milkshakes/
    - images/fruit_slush/
    - images/iced_tea/
    - images/big_plates/
    - images/snacks/
    - images/pasta/
    - images/sandwiches/
    - images/profile/
    - images/branches/
